name: Mirror Repositories
on:
  schedule:
    # nightly (0th hour 0th minute of every day)
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror
      run: |
        TOKEN=${{ secrets.TOKEN_FOR_MIRRORING }}
        if [ -z "${TOKEN}" ]; then
          echo "Token is unset. Can't do mirroring."
          exit 1
        fi
        GITLAB=https://gitlab.freedesktop.org/xorg
        GITHUB=https://x-access-token:$TOKEN@github.com/gitlab-freedesktop-mirrors

        function mirror {
          if [ "$3" == "" ]; then
            REMOTE=$GITLAB/$1/$2.git
          else
            REMOTE=$3
          fi
          git clone --mirror $REMOTE $2
          cd $2/
          git remote add github "$GITHUB/$2.git"
          git push --mirror github 
        }

        mirror proto xcbproto git://cgit.freedesktop.org/xcb/proto.git
